package com.joreksar.decomposetdlibproject.components

import com.arkivanov.decompose.ComponentContext
import com.joreksar.sharedtdlibfeatureapi.components.SharedTdlibFeatureComponent

expect fun createTdlibFeatureComponent(context: ComponentContext) : SharedTdlibFeatureComponent